<a href="https://colab.research.google.com/github/orifxonmarufxonov24-boop/gdp-dashboard/blob/phyton1/SIA_1_amaliy_Orifxon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import tensorflow as tf
import keras

print("Hammasi import bo‘ldi ")

Hammasi import bo‘ldi

In [1]:
from google.colab import files

files.download("data.csv")

FileNotFoundError: Cannot find file: data.csv

In [ ]:
df.to_csv("data.csv", index=False)

In [ ]:
import torch
print(torch.cuda.is_available())

In [ ]:
import pandas as pd

data = {
    "name": ["Ali", "Vali", "Hasan", "Husan", "Karim"],
    "age": [25, 32, 28, 45, 36],
    "salary": [300, 450, 380, 600, 520],
    "department": ["IT", "HR", "IT", "Finance", "HR"]
}

df = pd.DataFrame(data)
df

    name  age  salary department
0    Ali   25     300         IT
1   Vali   32     450         HR
2  Hasan   28     380         IT
3  Husan   45     600    Finance
4  Karim   36     520         HR

In [ ]:
selected = df[["age", "salary"]]
selected

   age  salary
0   25     300
1   32     450
2   28     380
3   45     600
4   36     520

In [ ]:
filtered = df[df["age"] > 30]
filtered

    name  age  salary department
1   Vali   32     450         HR
3  Husan   45     600    Finance
4  Karim   36     520         HR

In [ ]:
grouped = df.groupby("department")["salary"].mean()
grouped

department
Finance    600.0
HR         485.0
IT         340.0
Name: salary, dtype: float64

In [ ]:
df.loc[2, "salary"] = None
df

    name  age  salary department
0    Ali   25   300.0         IT
1   Vali   32   450.0         HR
2  Hasan   28     NaN         IT
3  Husan   45   600.0    Finance
4  Karim   36   520.0         HR

In [ ]:
df["salary"] = df["salary"].fillna(df["salary"].mean())
df

    name  age  salary department
0    Ali   25   300.0         IT
1   Vali   32   450.0         HR
2  Hasan   28   467.5         IT
3  Husan   45   600.0    Finance
4  Karim   36   520.0         HR

In [ ]:
df.loc[4, "salary"] = 2000
df

    name  age  salary department
0    Ali   25   300.0         IT
1   Vali   32   450.0         HR
2  Hasan   28   467.5         IT
3  Husan   45   600.0    Finance
4  Karim   36  2000.0         HR

In [ ]:
def remove_outliers_iqr(dataframe, column):
    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return dataframe[
        (dataframe[column] >= lower) &
        (dataframe[column] <= upper)
    ]

df_clean = remove_outliers_iqr(df, "salary")
df_clean

    name  age  salary department
0    Ali   25   300.0         IT
1   Vali   32   450.0         HR
2  Hasan   28   467.5         IT
3  Husan   45   600.0    Finance

In [ ]:
print(df.isnull().sum())

name          0
age           0
salary        0
department    0
dtype: int64

In [ ]:
df_dropna = df.dropna()
df_dropna

    name  age  salary department
0    Ali   25   300.0         IT
1   Vali   32   450.0         HR
2  Hasan   28   467.5         IT
3  Husan   45   600.0    Finance
4  Karim   36  2000.0         HR

In [ ]:
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("TensorFlow version:", tf.__version__)
print("Torch version:", torch.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.2
TensorFlow version: 2.19.0
Torch version: 2.10.0+cu128